name: meu_projeto
description: Desafio Técnico Escribo Estágio
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.16.10

dev_dependencies:
  # Dependências de desenvolvimento (como testes)
  # por exemplo:
  #   test: ^1.16.10
